{{- if .Values.elasticsearch.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: es-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  {{ toYaml .Values.elasticsearch.ssl.data | indent 2 }}
{{- end }}