{{- if .Values.elasticsearch.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opendistro-es.fullname" . }}-es-tls
  namespace: {{ .Release.Namespace }}
# type: kubernetes.io/tls
type: Opaque
data:
  # {{- range $k, $v := .Values.elasticsearch.ssl.data }}
  # {{ $k }}: {{ $v | b64enc }}
  # {{- end }}
  node-root-ca.pem: |-
    {{ .Values.elasticsearch.ssl.data.node-root-ca | b64enc }}
  node.pem: |-
    {{ .Values.elasticsearch.ssl.data.node | b64enc }}
  node-key.pem: |-
    {{ .Values.elasticsearch.ssl.data.node-key | b64enc }}
  admin-root-ca.pem: |-
    {{ .Values.elasticsearch.ssl.data.admin-root-ca | b64enc }}
  admin.pem: |-
    {{ .Values.elasticsearch.ssl.data.admin | b64enc }}
  admin-key.pem: |-
    {{ .Values.elasticsearch.ssl.data.admin-key | b64enc }}
{{- end }}