{{- if .Values.elasticsearch.securityConfig.internalUsersSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opendistro-es.fullname" . }}-es-internalusers
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
type: Opaque
data:
  internal_users.yml: {{ toYaml .Values.elasticsearch.securityConfig.internalUsersSecret | b64enc | quote }}
{{- end}}
