{{- if .Values.elasticsearch.performanceAnalyzerconfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opendistro-es.fullname" . }}-es-pa
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
type: Opaque
data:
  performance-analyzer.properties: {{ .Values.elasticsearch.performanceAnalyzerconfig.data.PAProperties | b64enc | quote }}
{{- end}}
