apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      # ttlSecondsAfterFinished: 600
      containers:
      - name: post-install-job
        image: {{ .Values.global.imageRegistry }}/{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.imageTag }}
        command:
          - /bin/sh
          - -c
          - |
            sleep 180 && \
            chmod a+x /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh && \
            /usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh \
            -cacert /usr/share/elasticsearch/config/admin-root-ca.pem \
            -cert /usr/share/elasticsearch/config/admin.pem \
            -key /usr/share/elasticsearch/config/admin-key.pem \
            -cd /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/ \
            -h {{ template "opendistro-es.fullname" . }}-discovery \
            -nhnv -icl
        volumeMounts:
        {{- if and .Values.elasticsearch.ssl.admin.enabled .Values.elasticsearch.ssl.admin.existingCertSecret }}
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/admin.pem
          name: admin-certs
          subPath: {{ .Values.elasticsearch.ssl.admin.existingCertSecretCertSubPath }}
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/admin-key.pem
          name: admin-certs
          subPath: {{ .Values.elasticsearch.ssl.admin.existingCertSecretKeySubPath }}
        - mountPath: {{ .Values.elasticsearch.configDirectory }}/admin-root-ca.pem
          name: admin-certs
          subPath: {{ .Values.elasticsearch.ssl.admin.existingCertSecretRootCASubPath }}
        {{- end }}
        {{- if .Values.elasticsearch.securityConfig.internalUsersSecret }}
        - mountPath: {{ .Values.elasticsearch.securityConfig.path }}/internal_users.yml
          name: internal-users-config
          subPath: internal_users.yml
        {{- end }}
      volumes:
      {{- if and .Values.elasticsearch.ssl.admin.enabled .Values.elasticsearch.ssl.admin.existingCertSecret }}
      - name: admin-certs
        secret:
          secretName: {{ template "opendistro-es.fullname" . }}-es-tls
      {{- end }}
      {{- if .Values.elasticsearch.securityConfig.internalUsersSecret }}
      - name: internal-users-config
        secret:
          secretName: {{ template "opendistro-es.fullname" . }}-es-internalusers
      {{- end }}
